let a = 30;
let b = "5"
console.log("a**b=",a**b)
console.log("a%b",a%b)
console.log("a==b is",a==b)
console.log("a!=b is",a!=b)
console.log(a>b && a!=b)
console.log(a<b || a!=b)
console.log("a===b is",a===b)
console.log("a!==b is",a!==b)
console.log("++a=",++a)
console.log("a++ =",a++)
console.log("a-- =",a--)
console.log("a =",a)
console.log("--a =",--a)
console.log("a=",a)
console.log("b**=5",b**=5)
console.log("a/=5",a/=5)
console.log("a%=30",a%=30)